export const actionTypes = {
    /*---------------------------------------------------------------------
                                HomeProcess
    -----------------------------------------------------------------------*/
    GET_AUTH_TOKEN_REQUEST: 'GET_AUTH_TOKEN_REQUEST',
    GET_AUTH_TOKEN_SUCCESS: 'GET_AUTH_TOKEN_SUCCESS',
    FETCH_SERVICES_ERROR: 'FETCH_SERVICES_ERROR',
    GET_AUFTRAG_DATA_REQUEST: 'GET_AUFTRAG_DATA_REQUEST',
    GET_AUFTRAG_DATA_SUCCESS: 'GET_AUFTRAG_DATA_SUCCESS',
    SAVE_ORDER_DETAIL_DATA_REQUEST: 'SAVE_ORDER_DETAIL_DATA_REQUEST',
    SAVE_ORDER_DETAIL_DATA_SUCCESS: 'SAVE_ORDER_DETAIL_DATA_SUCCESS',
    GET_FIRST_WEIGHT_DATA_REQUEST: 'GET_FIRST_WEIGHT_DATA_REQUEST',
    GET_FIRST_WEIGHT_DATA_SUCCESS: 'GET_FIRST_WEIGHT_DATA_SUCCESS',
    SAVE_SECOND_ORDER_DETAIL_DATA_REQUEST: 'SAVE_SECOND_ORDER_DETAIL_DATA_REQUEST',
    SAVE_SECOND_ORDER_DETAIL_DATA_SUCCESS: 'SAVE_SECOND_ORDER_DETAIL_DATA_SUCCESS',
    GET_ALL_ORDER_DETAIL_DATA_REQUEST: 'GET_ALL_ORDER_DETAIL_DATA_REQUEST',
    GET_ALL_ORDER_DETAIL_DATA_SUCCESS : 'GET_ALL_ORDER_DETAIL_DATA_SUCCESS'
}